# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

if [[ -v DISPLAY && ! -v SSH_TTY && ! -v SSH_CONNECTION ]] ; then
	xhost +local:0
fi
# Put your fun stuff here.
export EDITOR="/usr/bin/vim"
export LC_CTYPE="en_NZ.UTF8"
export __GL_FSAA_MODE=14
export __GL_LOG_MAX_ANISO=4
export __GL_ALLOW_UNOFFICIAL_PROTOCOL=1
source /home/kent/perl5/perlbrew/etc/bashrc
source /etc/profile.d/bash-completion.sh
